# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EmojiDictionary' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EmojiDictionary
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
end
